TK_D12/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('tinymce', include('tinymce.urls')),
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('schedule/', include('Schedule.urls')),
    path('doctor/', include('doctor.urls', namespace='doctor')),
    path('', include('article.urls', namespace='article')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'article'

urlpatterns = [
    path('article/', views.article, name='article'),
    path('news/<int:id>/', views.news, name='news'),
    path('tipsandtrick/<int:id>/', views.tipsandtrick, name='tipsandtrick'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index')
]

article/models.py
from django.db import models
from tinymce.models import models as tinymce_models, HTMLField

# Create your models here.
class News(models.Model):
    title = models.CharField(max_length=255, default="")
    date = models.DateField(auto_now_add=True)
    content = HTMLField('Content')
    image = models.ImageField(null=True, blank=True, upload_to='image')

    def __str__(self):
        return self.title

class TipsAndTrick(models.Model):
    title = models.CharField(max_length=255, default="")
    date = models.DateField(auto_now_add=True)
    content = HTMLField('Content')
    image = models.ImageField(null=True, blank=True, upload_to='image')

    def __str__(self):
        return self.title

article/views.py
from django.shortcuts import render
from .models import News, TipsAndTrick

# Create your views here.
def article(request):
    news = News.objects.all()
    tips = TipsAndTrick.objects.all()
    context = {
        "news": news,
        "tips": tips
    }
    return render(request, "article.html", context)

def news(request, id):
    news_detail = News.objects.get(id=id)
    context = {
        'news_detail': news_detail,
    }
    return render(request, 'news.html', context)

def tipsandtrick(request, id):
    tips_detail = TipsAndTrick.objects.get(id=id)
    context = {
        'tips_detail' : tips_detail
    }
    return render(request, 'tipsandtrick.html', context)

article/templates/article.html
{% extends 'home/base.html' %}
{% load static %}
<head>
    {% block css %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.min.css" rel="stylesheet">

    <!-- Font Google -->
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap" rel="stylesheet">

    <!-- Bootstrap Javascript -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <title>Article</title>

    <style>
        .news-image, .tips-image {
            width: 70%;
        }
        
        .news-title, .tips-title {
            padding-top: 1rem;
        }
        
        #news, #tipsandtrick {
            padding: 7% 15%;
        }
        
        #tipsandtrick {
            margin-bottom: 25%;
        }

        .news-box, .tips-box{
            text-align: center;
            font-family: "Lato", sans-serif;
            font-weight: bold;
            padding: 5%;
        }
    </style>
    {% endblock css %}
    
</head>

<body>

    

{% block content %}  
<section id="news">
    <h2>NEWS</h2>

    <div class="row">
        {% for item in news %}
        <div class="news-box col-lg-6">
          {% if item.image %}  
            <img class="news-image" src="{{item.image.url}}" alt="{{item.title}}">
          {% endif %}
          <a href="{% url 'article:news' item.id %}" item.id><h6 class="news-title">{{item.title}}</h6></a>
        </div>
        {% endfor %}
    </div>

</section>

<section id="tipsandtrick">
    <h2>TIPS AND TRICK</h2>

    <div class="row">
        {% for item in tips %}
        <div class="tips-box col-lg-6">
          {% if item.image %}  
            <img class="tips-image" src="{{item.image.url}}" alt="{{item.title}}">
          {% endif %}
          <a href="{% url 'article:tipsandtrick' item.id %}" item.id><h6 class="tips-title">{{item.title}}</h6></a>
        </div>
        {% endfor %}
    </div>
{% endblock content %}
</section>


</body>
</html>

article/templates/news.html
{% extends 'home/base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block css %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.min.css" rel="stylesheet">

    <!-- Bootstrap Javascript -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <title>{{news_detail.title}}</title>

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap');
        #detail {
            padding : 7% 15%;
            margin-bottom: 25%;
        }

        .detail-title {
            text-align: center;
            color: #154440;
        }

        .detail-image {
            width: 50%;
            display: block;
            margin-top: auto;
            margin-left: auto;
            margin-right: auto;
            text-align: center;
        }

        .content, .detail-title {
            font-family: "Lato", sans-serif;
        }

        .detail-title, .detail-date {
            font-weight: bold;
        }

        .content {
            font-size: larger;
            text-align: justify;
            color: black;
        }
    </style>
    {% endblock css %}
    
    
    
</head>
<body>
    {% block content %}
        <div id="detail">
            {% if news_detail.image %}
                <img src='{{news_detail.image.url}}' class="detail-image" alt="{{news_detail.title}}">
            {% endif %}
            <br> 
            <h1 class="detail-title">{{news_detail.title}}</h1>
            <br>
            <h6 class="detail-date">{{news_detail.date}}</h6>            
            <br>
            <div class="content">
                {% autoescape off %}
                {{news_detail.content | safe}}
                {% endautoescape %}
            </div>
        </div>

    {% endblock content %}
</body>
</html>

article/templates/tipsandtrick.html
{% extends 'home/base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block css %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.min.css" rel="stylesheet">

    <!-- Bootstrap Javascript -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    
    <title>{{tips_detail.title}}</title>

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap');
        #detail {
            padding : 7% 15%;
            margin-bottom: 25%;
        }

        .detail-title {
            text-align: center;
            color: #154440;
        }

        .detail-image {
            width: 50%;
            display: block;
            margin-top: auto;
            margin-left: auto;
            margin-right: auto;
            text-align: center;
        }

        .content, .detail-title {
            font-family: "Lato", sans-serif;
        }

        .detail-title, .detail-date {
            font-weight: bold;
        }

        .content {
            font-size: larger;
            text-align: justify;
            color: black;
        }
    </style>
    
    {% endblock css %}
    

    
</head>
<body>
    
    
    
    {% block content %}
    <div id="detail">
        {% if tips_detail.image %}
            <img src='{{tips_detail.image.url}}' class="detail-image" alt="{{tips_detail.title}}">
        {% endif %}
        <br> <br>
        <h1 class="detail-title">{{tips_detail.title}}</h1>
        <br>
        <h6 class="detail-date">{{tips_detail.date}}</h6>            
        <br>
        <div class="content">
            {% autoescape off %}
            {{tips_detail.content | safe}}
            {% endautoescape %}
        </div>
    </div>
    {% endblock content %}
</body>
</html>